import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const author = { name: 'Thales Zarzar', url: 'https://github.com/ThalesZZ' }
export const metadata: Metadata = {
  title: 'Network Speed Tracker',
  description: 'Generated by create next app',
  authors: [author],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>): React.ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <footer>
          Developed by <a href={author.url}>{author.name}</a>
        </footer>
      </body>
    </html>
  )
}
